# TODO redeploy this, then move to the main helm values. See if operator makes any changes during this transition
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: seedbox
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
    deviceClass: ssd
  dataPools:
    - replicated:
        size: 2
      deviceClass: hdd
      parameters:
        min_size: "1"
  metadataServer:
    activeCount: 1
    activeStandby: true
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: storage-node
              operator: In
              values:
              - "true"
      tolerations:
      - key: storage-node
        operator: Exists
