apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: ceph-objectstore
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
    deviceClass: ssd
    failureDomain: host
  dataPool:
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
    deviceClass: hdd
    failureDomain: host
  preservePoolsOnDelete: true
  gateway:
    sslCertificateRef:
    port: 6980
    # securePort: 443
    instances: 1
  #healthCheck:
  #  bucket:
  #    disabled: false
  #    interval: 60s
