---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rook-ceph-dashboard
  namespace: rook-ceph
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`ceph.lan.jibby.org`)
    services:
    - kind: Service
      name: rook-ceph-mgr-dashboard
      port: 8080
    middlewares:
    - name: lanonly
      namespace: kube-system
