# TODO move to the main helm values
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: proxmox
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
  deviceClass: hdd
