apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 40Ti
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-pvc
    namespace: plex
  csi:
    controllerExpandSecretRef:
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      fsName: data
      pool: data-data0
      storage.kubernetes.io/csiProvisionerIdentity: 1695249079096-8081-rook-ceph.cephfs.csi.ceph.com
      subvolumeName: csi-vol-43ed95f1-5ff2-11ee-a6fc-36612df83157
      subvolumePath: /volumes/csi/csi-vol-43ed95f1-5ff2-11ee-a6fc-36612df83157/260d0fc9-028c-43ed-bab3-f904bf4d0f8f
    volumeHandle: 0001-0009-rook-ceph-0000000000000003-43ed95f1-5ff2-11ee-a6fc-36612df83157
  persistentVolumeReclaimPolicy: Retain
  storageClassName: data-sc
  volumeMode: Filesystem
