apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: delugevpn-pvc
  namespace: plex
  labels:
    app: delugevpn
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
