---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delugevpn
  namespace: plex
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: delugevpn
  replicas: 1
  template:
    metadata:
      labels:
        app: delugevpn
      annotations:
        backup.velero.io/backup-volumes-excludes: seedbox
    spec:
      containers:
      - name: delugevpn
        image: binhex/arch-delugevpn:2.1.1-6-05
        ports:
        - containerPort: 8112
          name: http-web-svc
        securityContext:
          privileged: true
        envFrom:
        - secretRef:
            name: delugevpn-secret
        volumeMounts:
        - mountPath: "/data"
          name: seedbox
        - mountPath: "/config"
          name: config
        resources:
          requests:
            memory: "0"
          limits:
            memory: "6Gi"
      volumes:
      - name: seedbox
        persistentVolumeClaim:
          claimName: seedbox-pvc
      - name: config
        persistentVolumeClaim:
          claimName: delugevpn-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: delugevpn-service
  namespace: plex
spec:
  selector:
    app: delugevpn
  type: ClusterIP
  ports:
  - name: delugevpn-web-port
    protocol: TCP
    port: 8112
    targetPort: http-web-svc
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: delugevpn
  namespace: plex
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`delugevpn.lan.jibby.org`)
    services:
    - kind: Service
      name: delugevpn-service
      port: 8112
    middlewares:
    - name: lanonly
      namespace: kube-system
