---
apiVersion: v1
kind: Namespace
metadata:
    name: diun
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diun-pvc
  namespace: diun
  labels:
    app: diun
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi