apiVersion: v1
kind: Namespace
metadata:
    name: homeassistant
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pvc
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  storageClassName: ceph-block-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
