apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-pvc
  namespace: plex
  labels:
    app: lidarr
spec:
  storageClassName: ceph-block-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
