---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: plex
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: lidarr
  replicas: 1
  template:
    metadata:
      labels:
        app: lidarr
      annotations:
        backup.velero.io/backup-volumes-excludes: plex,seedbox,scratch
    spec:
      containers:
      - name: lidarr
        image: lscr.io/linuxserver/lidarr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8686
          name: http-web-svc
        env:
        - name: TZ
          value: America/New_York
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - mountPath: "/plex"
          name: plex
        - mountPath: "/seedbox"
          name: seedbox
        - mountPath: "/config"
          name: config
        - mountPath: "/scratch"
          name: scratch
        resources:
          requests:
            memory: "0"
          limits:
            memory: "1Gi"
      volumes:
      - name: plex
        persistentVolumeClaim:
          claimName: plex-pvc
      - name: seedbox
        persistentVolumeClaim:
          claimName: seedbox-pvc
      - name: config
        persistentVolumeClaim:
          claimName: lidarr-pvc
      - name: scratch
        nfs:
          server: 172.16.69.52
          path: /data/torrents
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr-service
  namespace: plex
spec:
  selector:
    app: lidarr
  type: ClusterIP
  ports:
  - name: lidarr-web-port
    protocol: TCP
    port: 8686
    targetPort: http-web-svc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lidarr
  namespace: plex
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-lanonly@kubernetescrd
spec:
  rules:
    - host: lidarr.lan.jibby.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lidarr-service
                port:
                  number: 8686
