version: '3.7'

# Made to be run with docker-compose, for GPU passthrough.

networks:
  media:
    driver: overlay

services:
  plex:
    image: linuxserver/plex:amd64-version-1.25.6.5577-c8bd13540
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    expose:
      - "32400"
    ports:
      - mode: host
        published: 32400
        target: 32400
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${CONTAINERS_DIR}/plex:/config
      - ${MEDIA_DIR}/Video/Movies:/movies
      - ${MEDIA_DIR}/Video/Shows:/tv
      - ${MEDIA_DIR}/Video/Anime:/Anime
      - type: tmpfs
        target: /transcodes
        tmpfs:
          size: 12000000000 # ~12gb
    restart: always
    networks:
      - media

  jellyfin:
    image: jellyfin/jellyfin:10.7.7
    # GPU encoding doesn't work currently
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    expose:
      - "8096"
    user: 1000:1000
    ports:
      - mode: host
        published: 8096
        target: 8096
    tmpfs:
      - /transcodes:mode=770,size=12000000000,uid=1000,gid=1000
    volumes:
      - ${CONTAINERS_DIR}/jellyfin:/config
      - ${MEDIA_DIR}:/media
    restart: always
    networks:
      - media

  jellyfixer:
    image: quay.io/xsteadfastx/jellyfixer:latest
    command: http://jellyfin:8096/jellyfin
    expose:
      - "8088"
    ports:
      - mode: host
        published: 8088
        target: 8088
    environment:
      - JELLYFIXER_INTERNAL_URL=http://jellyfin:8096/jellyfin
      - JELLYFIXER_EXTERNAL_URL=https://jellyfin.${DOMAIN}/jellyfin
    restart: always
    networks:
      - media
