---
apiVersion: v1
kind: Namespace
metadata:
    name: miniflux
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
  namespace: miniflux
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: miniflux
  replicas: 1
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      containers:
      - name: miniflux
        image: miniflux/miniflux:2.1.1
        ports:
        - containerPort: 8080
          name: http-web-svc
        envFrom:
        - secretRef:
            name: miniflux-db-secret
        env:
        - name: RUN_MIGRATIONS
          value: "1"
        - name: BASE_URL
          value: https://miniflux.jibby.org
        livenessProbe:
          exec:
            command: ["/usr/bin/miniflux", "-healthcheck", "auto"]
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux-service
  namespace: miniflux
spec:
  selector:
    app: miniflux
  type: ClusterIP
  ports:
  - name: miniflux-web-port
    protocol: TCP
    port: 8080
    targetPort: http-web-svc
