---
apiVersion: v1
kind: Namespace
metadata:
    name: ntfy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-pvc
  namespace: ntfy
  labels:
    app: ntfy
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi