---
apiVersion: v1
kind: Namespace
metadata:
    name: ooniprobe
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ooniprobe-pvc
  namespace: ooniprobe
  labels:
    app: ooniprobe
spec:
  storageClassName: ceph-block-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
