---
apiVersion: v1
kind: Namespace
metadata:
    name: paperless
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-pvc
  namespace: paperless
  labels:
    app: paperless
spec:
  storageClassName: ceph-block-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

