---
apiVersion: v1
kind: Namespace
metadata:
    name: plex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  replicas: 1
  template:
    metadata:
      labels:
        app: plex
      annotations:
        backup.velero.io/backup-volumes-excludes: media,media-metadata,transcodes
    spec:
      containers:
      - name: plex
        image: linuxserver/plex:latest
        imagePullPolicy: Always
        # for debugging
        # command: ["/bin/sh"]
        # args: ["-c", "sleep 3600"]
        ports:
        - containerPort: 32400
          name: http-web-svc
        volumeMounts:
        - mountPath: "/config"
          name: config
        - mountPath: "/config/Library/Application Support/Plex Media Server/Media"
          name: media-metadata
        - mountPath: "/media"
          name: media
        - mountPath: "/transcodes"
          name: transcodes
        # Quicksync
        - name: "render-device"
          mountPath: "/dev/dri/renderD128"
        # Quicksync
        securityContext:
            privileged: true
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        livenessProbe:
          httpGet:
            path: /web/index.html
            port: 32400
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        resources:
          limits:
            ephemeral-storage: "10Gi"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu-node
                operator: In
                values:
                - "true"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: plex-config-pvc
      - name: media-metadata
        persistentVolumeClaim:
          claimName: plex-metadata-pvc
      - name: media
        persistentVolumeClaim:
          claimName: plex-pvc
          readOnly: true
      - name: transcodes
        emptyDir: {}
      # Quicksync
      - name: "render-device"
        hostPath:
          path: "/dev/dri/renderD128"
---
apiVersion: v1
kind: Service
metadata:
  name: plex-service
  namespace: plex
spec:
  selector:
    app: plex
  type: ClusterIP
  ports:
  - name: plex-web-port
    protocol: TCP
    port: 32400
    targetPort: http-web-svc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  namespace: plex
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: plex.jibby.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex-service
                port:
                  number: 32400
