---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: plex
spec:
  selector:
    matchLabels:
      app: prowlarr
  replicas: 1
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:nightly-1.10.3.4070-ls21
        ports:
        - containerPort: 9696
          name: http-web-svc
        env:
        - name: TZ
          value: America/New_York
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - mountPath: "/config"
          name: config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prowlarr-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr-service
  namespace: plex
spec:
  selector:
    app: prowlarr
  type: ClusterIP
  ports:
  - name: prowlarr-web-port
    protocol: TCP
    port: 9696
    targetPort: http-web-svc
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  namespace: plex
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`prowlarr.lan.jibby.org`)
    services:
    - kind: Service
      name: prowlarr-service
      port: 9696

