apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrentvpn-pvc
  namespace: plex
  labels:
    app: qbittorrentvpn
spec:
  storageClassName: ceph-block-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
