---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: plex
spec:
  selector:
    matchLabels:
      app: radarr
  replicas: 1
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:nightly-4.4.0.6875-ls428
        ports:
        - containerPort: 7878
          name: http-web-svc
        env:
        - name: TZ
          value: America/New_York
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - mountPath: "/plex"
          name: plex
        - mountPath: "/config"
          name: config
      volumes:
      - name: plex
        persistentVolumeClaim:
          claimName: plex-pvc
      - name: config
        persistentVolumeClaim:
          claimName: radarr-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-service
  namespace: plex
spec:
  selector:
    app: radarr
  type: ClusterIP
  ports:
  - name: radarr-web-port
    protocol: TCP
    port: 7878
    targetPort: http-web-svc