---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: plex
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: radarr
  replicas: 1
  template:
    metadata:
      labels:
        app: radarr
      annotations:
        backup.velero.io/backup-volumes-excludes: plex
    spec:
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:nightly-5.8.3.8932-ls42
        ports:
        - containerPort: 7878
          name: http-web-svc
        env:
        - name: TZ
          value: America/New_York
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - mountPath: "/plex"
          name: plex
        - mountPath: "/config"
          name: config
      volumes:
      - name: plex
        persistentVolumeClaim:
          claimName: plex-pvc
      - name: config
        persistentVolumeClaim:
          claimName: radarr-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-service
  namespace: plex
spec:
  selector:
    app: radarr
  type: ClusterIP
  ports:
  - name: radarr-web-port
    protocol: TCP
    port: 7878
    targetPort: http-web-svc
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
  namespace: plex
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`radarr.lan.jibby.org`)
    services:
    - kind: Service
      name: radarr-service
      port: 7878

