---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seedbox-pvc
  namespace: plex
spec:
  storageClassName: seedbox-sc
  volumeName: seedbox-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Ti
