---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shelly-plug-exporter
  namespace: homeassistant
  annotations:
    prometheus.io/path: /probe
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: shelly-plug-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: shelly-plug-exporter
    spec:
      containers:
      - name: shelly-plug-exporter
        image: webdevops/shelly-plug-exporter:24.9.0
        ports:
        - containerPort: 8080
          name: metrics
        env:
        - name: SHELLY_HOST_SHELLYPLUSES
          value: 172.16.69.80,172.16.69.81,172.16.69.82,172.16.69.83,172.16.69.84
        - name: SHELLY_AUTH_USERNAME
          value: admin
        - name: SHELLY_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shelly-plug-exporter
              key: password
              optional: false
        - name: LOG_DEBUG
          value: "1"
        - name: LOG_JSON
          value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: shelly-plug-exporter
  namespace: homeassistant
  labels:
    app: shelly-plug-exporter
spec:
  selector:
    app: shelly-plug-exporter
  type: ClusterIP
  ports:
  - name: metrics
    protocol: TCP
    port: 8080
    targetPort: metrics
