---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: plex
spec:
  selector:
    matchLabels:
      app: sonarr
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarr
      annotations:
        backup.velero.io/backup-volumes-excludes: plex
    spec:
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:develop-4.0.0.752-ls25
        ports:
        - containerPort: 8989
          name: http-web-svc
        env:
        - name: TZ
          value: America/New_York
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - mountPath: "/plex"
          name: plex
        - mountPath: "/config"
          name: config
      volumes:
      - name: plex
        persistentVolumeClaim:
          claimName: plex-pvc
      - name: config
        persistentVolumeClaim:
          claimName: sonarr-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
  namespace: plex
spec:
  selector:
    app: sonarr
  type: ClusterIP
  ports:
  - name: sonarr-web-port
    protocol: TCP
    port: 8989
    targetPort: http-web-svc
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: plex
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`sonarr.lan.jibby.org`)
    services:
    - kind: Service
      name: sonarr-service
      port: 8989
