---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: plex
spec:
  selector:
    matchLabels:
      app: sonarr
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:4.0.0-v4
        ports:
        - containerPort: 8989
          name: http-web-svc
        command:
        - "/bin/bash"
        - "-c"
        # Mount an sshfs connection to the seedbox
        - "apk update && apk add sshfs && cp remote-secrets/REMOTE_KEY /key && chown 600 /key && mkdir /remote && chown 1000:1000 /remote && sshfs -o allow_other,default_permissions,uid=1000,gid=1000,umask=002 $REMOTE -o IdentityFile=/key -o StrictHostKeyChecking=no /remote && /init"
        env:
        - name: TZ
          value: America/New_York
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - mountPath: "/plex"
          name: plex
        - mountPath: "/config"
          name: config
        - name: remote-secret
          mountPath: /remote-secrets
        envFrom:
        - secretRef:
            name: sonarr-remote-secret
        securityContext:
          privileged: true  # required for sshfs mount
      volumes:
      - name: plex
        persistentVolumeClaim:
          claimName: plex-pvc
      - name: config
        persistentVolumeClaim:
          claimName: sonarr-pvc
      - name: remote-secret
        secret:
          secretName: sonarr-remote-secret
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
  namespace: plex
spec:
  selector:
    app: sonarr
  type: ClusterIP
  ports:
  - name: sonarr-web-port
    protocol: TCP
    port: 8989
    targetPort: http-web-svc
