[http]
  [http.routers]
    [http.routers.ceph]
      rule = "Host(`s3.${DOMAIN}`)"
      service = "ceph"
      [http.routers.ceph.tls]
    [http.routers.swarmpit]
      rule = "Host(`swarmpit.${DOMAIN}`)"
      service = "swarmpit"
      [http.routers.swarmpit.tls]
  [http.services]
    [http.services.ceph]
      [http.services.ceph.loadBalancer]
        passHostHeader = true
        [[http.services.ceph.loadBalancer.servers]]
          # Any one of the ceph nodes
          url = "http://172.16.69.30:7480"
    [http.services.swarmpit]
      [http.services.swarmpit.loadBalancer]
        passHostHeader = true
        [[http.services.swarmpit.loadBalancer.servers]]
          # The external IP of the swarm setup
          url = "http://172.16.69.253:888"
