[http]
  [http.routers]
    [http.routers.ceph]
      rule = "Host(`s3.${DOMAIN}`)"
      service = "ceph"
      [http.routers.ceph.tls]
    [http.routers.swarmpit]
      rule = "Host(`swarmpit.${DOMAIN}`)"
      service = "swarmpit"
      [http.routers.swarmpit.tls]
    [http.routers.jellyfin]
      rule = "Host(`jellyfin.${DOMAIN}`)"
      service = "jellyfin"
      [http.routers.jellyfin.tls]
    [http.routers.jellyfixer]
      rule = "Host(`jellyfin.${DOMAIN}`)  && Path(`/jellyfin/System/Info/Public`)"
      service = "jellyfixer"
      [http.routers.jellyfixer.tls]
    [http.routers.plex]
      rule = "Host(`plex.${DOMAIN}`)"
      service = "plex"
      [http.routers.plex.tls]
  [http.services]
    [http.services.ceph]
      [http.services.ceph.loadBalancer]
        passHostHeader = true
        # One or more ceph nodes
        [[http.services.ceph.loadBalancer.servers]]
          url = "http://${CEPH1}:7480"
        [[http.services.ceph.loadBalancer.servers]]
          url = "http://${CEPH2}:7480"
    [http.services.swarmpit]
      [http.services.swarmpit.loadBalancer]
        passHostHeader = true
        [[http.services.swarmpit.loadBalancer.servers]]
          url = "http://${EXTERNAL_SWARM_IP}:888"
    [http.services.jellyfin]
      [http.services.jellyfin.loadBalancer]
        passHostHeader = true
        [[http.services.jellyfin.loadBalancer.servers]]
          url = "http://${MEDIA_IP}:8096"
    [http.services.jellyfixer]
      [http.services.jellyfixer.loadBalancer]
        passHostHeader = true
        [[http.services.jellyfixer.loadBalancer.servers]]
          url = "http://${MEDIA_IP}:8088"
    [http.services.plex]
      [http.services.plex.loadBalancer]
        passHostHeader = true
        [[http.services.plex.loadBalancer.servers]]
          url = "http://${MEDIA_IP}:32400"
