---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-pvc
  namespace: plex
  labels:
    app: syncthing
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi