---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: plex
  name: syncthing
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
      annotations:
        backup.velero.io/backup-volumes-excludes: data
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cluster-ingress
                operator: In
                values:
                - "true"
      hostNetwork: true
      containers:
        - name: syncthing
          image: linuxserver/syncthing:1.27.2
          imagePullPolicy: Always
          ports:
          - containerPort: 8384
            name: http-web-svc
          - containerPort: 22000
            name: transfer-svc
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - mountPath: "/data"
              name: "data"
            - mountPath: "/config"
              name: "config"
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-pvc
      - name: config
        persistentVolumeClaim:
          claimName: syncthing-pvc
