---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  namespace: plex
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tautulli
  replicas: 1
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      containers:
      - name: tautulli
        image: linuxserver/tautulli:latest
        ports:
        - containerPort: 8181
          name: http-web-svc
        env:
        - name: TZ
          value: America/New_York
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - mountPath: "/config"
          name: config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: tautulli-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tautulli-service
  namespace: plex
spec:
  selector:
    app: tautulli
  type: ClusterIP
  ports:
  - name: tautulli-web-port
    protocol: TCP
    port: 8181
    targetPort: http-web-svc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tautulli
  namespace: plex
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-lanonly@kubernetescrd
spec:
  rules:
    - host: tautulli.lan.jibby.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tautulli-service
                port:
                  number: 8181
