apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  octoprint.yaml: |
    http:
      routers:
        octoprint:
          rule: Host(`octoprint.lan.jibby.org`)
          service: octoprint
      services:
        octoprint:
          loadBalancer:
            servers:
              - url: http://172.16.69.49
  pikvm.yaml: |
    http:
      routers:
        pikvm:
          rule: Host(`pikvm.lan.jibby.org`)
          service: pikvm
      services:
        pikvm:
          loadBalancer:
            serversTransport: "pikvm"
            servers:
              - url: https://172.16.69.240
      serversTransports:
        pikvm:
          insecureSkipVerify: true
  proxmox.yaml: |
    http:
      routers:
        proxmox:
          rule: Host(`proxmox.lan.jibby.org`)
          service: proxmox
      services:
        proxmox:
          loadBalancer:
            serversTransport: "proxmox"
            servers:
              - url: https://172.16.69.40:8006
      serversTransports:
        proxmox:
          insecureSkipVerify: true
  ceph.yaml: |
    http:
      routers:
        ceph:
          rule: Host(`ceph.lan.jibby.org`)
          service: ceph
      services:
        ceph:
          loadBalancer:
            serversTransport: "ceph"
            servers:
              - url: https://172.16.69.30:8443
              - url: https://172.16.69.31:8443
              - url: https://172.16.69.32:8443
      serversTransports:
        ceph:
          insecureSkipVerify: true
