apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: selfoss-pvc
  namespace: selfoss
  labels:
    app: selfoss
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
