---
apiVersion: v1
kind: Namespace
metadata:
    name: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: "quay.io/minio/minio:RELEASE.2024-01-16T16-07-38Z"
        command: ["minio", "server", "/data", "--console-address", ":9090"]
        ports:
        - containerPort: 9000
          name: http-web-svc
        - containerPort: 9090
          name: http-con-svc
        envFrom:
        - secretRef:
            name: minio-secret
        env:
        volumeMounts:
        - mountPath: "/data"
          name: data
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          limits:
            memory: 7Gi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio
spec:
  selector:
    app: minio
  type: ClusterIP
  ports:
  - name: minio-web-port
    protocol: TCP
    port: 9000
    targetPort: http-web-svc
  - name: minio-con-port
    protocol: TCP
    port: 9090
    targetPort: http-con-svc
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: minio
  namespace: minio
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`s3.bnuuy.org`)
    services:
    - kind: Service
      name: minio-service
      port: 9000
