---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s3
  namespace: rook-ceph
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: s3.jibby.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rook-ceph-rgw-ceph-objectstore-ec
                port:
                  number: 6981
