apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-metadata-static-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Ti
  csi:
    controllerExpandSecretRef:
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      fsName: media
      pool: media-data0
      storage.kubernetes.io/csiProvisionerIdentity: 1657147448506-8081-rook-ceph.cephfs.csi.ceph.com
      subvolumeName: csi-vol-9b2f40f9-0613-11ed-8662-4a986e7745e3
      subvolumePath: /volumes/csi/csi-vol-9b2f40f9-0613-11ed-8662-4a986e7745e3/07b0a3bf-e458-4442-90df-f70aaa971da6
    volumeHandle: 0001-0009-rook-ceph-0000000000000002-9b2f40f9-0613-11ed-8662-4a986e7745e3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-sc
  volumeMode: Filesystem
