apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rook-ceph.cephfs.csi.ceph.com
  name: plex-static-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Ti
  csi:
    controllerExpandSecretRef:
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      fsName: plex
      pool: plex-erasurecoded
      storage.kubernetes.io/csiProvisionerIdentity: 1662922724498-8081-rook-ceph.cephfs.csi.ceph.com
      subvolumeName: csi-vol-75be7e58-3548-11ed-8f63-2e9244479848
      subvolumePath: /volumes/csi/csi-vol-75be7e58-3548-11ed-8f63-2e9244479848/e9eef038-dd57-4e89-94ea-08011a6b6e74
    volumeHandle: 0001-0009-rook-ceph-0000000000000006-75be7e58-3548-11ed-8f63-2e9244479848
  persistentVolumeReclaimPolicy: Retain
  storageClassName: plex-sc
  volumeMode: Filesystem
