---
apiVersion: v1
kind: Namespace
metadata:
    name: miniflux
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
  namespace: miniflux
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: miniflux
  replicas: 1
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      containers:
      - name: miniflux
        image: miniflux/miniflux:2.1.1
        ports:
        - containerPort: 8080
          name: http-web-svc
        envFrom:
        - secretRef:
            name: miniflux-db-secret
        env:
        - name: RUN_MIGRATIONS
          value: "1"
        - name: BASE_URL
          value: https://miniflux.jibby.org
        livenessProbe:
          exec:
            command: ["/usr/bin/miniflux", "-healthcheck", "auto"]
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux-service
  namespace: miniflux
spec:
  selector:
    app: miniflux
  type: ClusterIP
  ports:
  - name: miniflux-web-port
    protocol: TCP
    port: 8080
    targetPort: http-web-svc
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-db-secret
  namespace: miniflux
spec:
  target:
    name: miniflux-db-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        DATABASE_URL: |-
          postgres://{{ .username }}:{{ .password }}@postgres-postgresql.postgres.svc.cluster.local:5432/miniflux?sslmode=disable
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 8d733830-0f81-4de7-93e2-b3f8007a08b1
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 8d733830-0f81-4de7-93e2-b3f8007a08b1
        property: password
