apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: immich
  namespace: immich
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`immich.jibby.org`)
    services:
    - kind: Service
      name: immich-server
      port: 3001
