---
apiVersion: v1
kind: Namespace
metadata:
    name: immich
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pvc
  namespace: immich
  labels:
    app: immich
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
