kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plexmd-base-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
  storageClassName: media-sc
  volumeMode: Filesystem