apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: ceph-objectstore-ec
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
    failureDomain: osd
  dataPool:
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
    failureDomain: osd
  preservePoolsOnDelete: true
  gateway:
    sslCertificateRef:
    port: 6981
    # securePort: 443
    instances: 1
  #healthCheck:
  #  bucket:
  #    disabled: false
  #    interval: 60s
