---
- name: Install apt-add-repository & nice to haves
  apt:
    name: '{{ packages }}'
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - nethogs
      - tree
      - memtest86+
      - dnsutils
      - jq

- name: Add Docker's GPG key
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
  args:
    warn: False  # Piping

- name: Add Docker's apt repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

- name: Install Docker
  apt:
    name: '{{ packages }}'
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Add '{{ user }}' to docker group
  user:
    name: '{{ user }}'
    groups: docker
    append: yes

- name: Install docker-compose
  shell: curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
  args:
    warn: False  # Calls to uname

# TODO pull https://gogs.jibby.org/jhb2345/dotfiles

# TODO stow profile, dircolors, zsh, antigen, vim

# TODO set zsh as default shell

# TODO mount the ceph cluster

- name: Install ceph-ensure-mount service
  copy:
    src: templates/basic/ceph-ensure-mount.service
    dest: /etc/systemd/system/ceph-ensure-mount.service
    mode: "0700"
    owner: root
    group: root

- name: systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable ceph-ensure-mount service
  ansible.builtin.systemd:
    name: ceph-ensure-mount
    state: started
    enabled: yes
