apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-static-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Ti
  csi:
    controllerExpandSecretRef:
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      fsName: media
      pool: media-data0
      storage.kubernetes.io/csiProvisionerIdentity: 1657147447431-8081-rook-ceph.cephfs.csi.ceph.com
      subvolumeName: csi-vol-474d5ba4-fe4f-11ec-9369-b20c27405718
      subvolumePath: /volumes/csi/csi-vol-474d5ba4-fe4f-11ec-9369-b20c27405718/ed910e5e-ebd1-40b5-9b58-464534002120
    volumeHandle: 0001-0009-rook-ceph-0000000000000002-474d5ba4-fe4f-11ec-9369-b20c27405718
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-sc
  volumeMode: Filesystem
