---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-pvc
  namespace: plex
  labels:
    app: audiobookshelf
spec:
  storageClassName: ceph-block-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
