apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-persistant
  namespace: monitoring
spec:
  replicas: 1
  retention: 365d
  resources:
    requests:
      memory: '0'
    limits:
      memory: 1Gi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: alertmanager-operated
        port: web
  serviceAccountName: prometheus
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
  ruleSelector: # {} # does this pick up nothing if nil?
    matchLabels:
      role: alert-rules
  ruleNamespaceSelector: {}
  #  matchExpressions:
  #  - key: name
  #    operator: In
  #    values:
  #    - kube-state-metrics
  #    - node-exporter
  #    - kubelet
  #    - traefik
  #    - rook-ceph-mgr
  #    - rook-ceph-exporter
  #    - cloudflared
  #    - shelly-plug-exporter
  #  matchExpressions:
  #  - key: kubernetes.io/metadata.name
  #    operator: In
  #    values:
  #    - monitoring
  #    - rook-ceph
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ceph-block
        resources:
          requests:
            storage: 100Gi
