# TODO move to the main helm values
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: seedbox
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
    deviceClass: ssd
  dataPools:
    - replicated:
        size: 2
      deviceClass: hdd
      parameters:
        # had constant 50% misplaced objects when size=2, min_size=1
        min_size: "2"
  metadataServer:
    activeCount: 1
    activeStandby: true
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: storage-node
              operator: In
              values:
              - "true"
      tolerations:
      - key: storage-node
        operator: Exists
