# https://github.com/cloudflare/argo-tunnel-examples/blob/master/named-tunnel-k8s/cloudflared.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 3
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        ports:
        - containerPort: 2000
          name: metrics
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
      volumes:
      - name: creds
        secret:
          secretName: tunnel-credentials
      - name: config
        configMap:
          name: cloudflared
          items:
          - key: config.yaml
            path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: kube-system
data:
  config.yaml: |
    tunnel: example-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    ingress:
    - hostname: gogs.jibby.org
      service: http://gogs-service.gogs.svc.cluster.local:3000
    - hostname: miniflux.jibby.org
      service: http://miniflux-service.miniflux.svc.cluster.local:8080
    - hostname: ntfy-alertmanager.jibby.org
      service: http://ntfy-alertmanager.monitoring.svc.cluster.local:80
    - hostname: homeassistant.jibby.org
      service: http://homeassistant-service.homeassistant.svc.cluster.local:8123
    - hostname: ntfy.jibby.org
      service: http://ntfy-service.ntfy.svc.cluster.local:80
    - hostname: paperless.jibby.org
      service: http://paperless-service.paperless.svc.cluster.local:8000
    - hostname: tronbyt.jibby.org
      service: http://tronbyt-service.tronbyt.svc.cluster.local:8000
    - hostname: uptime.jibby.org
      service: http://uptime-kuma-service.uptime-kuma.svc.cluster.local:3001
    - hostname: status.jibby.org
      service: http://uptime-kuma-service.uptime-kuma.svc.cluster.local:3001
    - hostname: argocd.jibby.org
      path: api/badge
      service: http://argocd-server.argocd.svc.cluster.local:80
    - service: http_status:404
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunnel-credentials
  namespace: kube-system
spec:
  target:
    name: tunnel-credentials
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        credentials.json: |-
          {{ .credentials }}
  data:
    - secretKey: credentials
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: 4a0b91df-6fcb-4dc1-a0b7-b3f800730cc1
