---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshelf
  namespace: plex
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bookshelf
  replicas: 1
  template:
    metadata:
      labels:
        app: bookshelf
      annotations:
        backup.velero.io/backup-volumes-excludes: plex,seedbox
    spec:
      containers:
      - name: bookshelf
        image: ghcr.io/pennydreadful/bookshelf:hardcover
        imagePullPolicy: Always
        ports:
        - containerPort: 8787
          name: http-web-svc
        env:
        - name: TZ
          value: America/New_York
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - mountPath: /audiobooks
          name: media
          subPath: Audiobooks
        - mountPath: /scratch
          name: seedbox
          subPath: audiobooks
        - mountPath: /config
          name: config
        resources:
          requests:
            memory: "0"
          limits:
            memory: "2Gi"
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: plex-pvc
      - name: config
        persistentVolumeClaim:
          claimName: bookshelf-pvc
      - name: seedbox
        nfs:
          server: 172.16.69.253
          path: /seedbox/torrents
---
apiVersion: v1
kind: Service
metadata:
  name: bookshelf-service
  namespace: plex
spec:
  selector:
    app: bookshelf
  type: ClusterIP
  ports:
  - name: bookshelf-web-port
    protocol: TCP
    port: 8787
    targetPort: http-web-svc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookshelf
  namespace: plex
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-lanonly@kubernetescrd
spec:
  rules:
    - host: bookshelf.lan.jibby.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bookshelf-service
                port:
                  number: 8787
